import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gungeon_search, GungeonSearchWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production config (DATABASE_URL, SECRET_KEY_BASE, PHX_HOST, etc.)
# lives in config/runtime.exs, which is evaluated at boot for both `mix
# phx.server` and `mix release` builds.
